// Code generated by protoc-gen-go. DO NOT EDIT.
// source: herdcommand.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HerdCommand struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data1                int64    `protobuf:"varint,2,opt,name=data1,proto3" json:"data1,omitempty"`
	Data2                int64    `protobuf:"varint,3,opt,name=data2,proto3" json:"data2,omitempty"`
	Deadline             int64    `protobuf:"varint,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HerdCommand) Reset()         { *m = HerdCommand{} }
func (m *HerdCommand) String() string { return proto.CompactTextString(m) }
func (*HerdCommand) ProtoMessage()    {}
func (*HerdCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2a1723f8d5a273c, []int{0}
}

func (m *HerdCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HerdCommand.Unmarshal(m, b)
}
func (m *HerdCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HerdCommand.Marshal(b, m, deterministic)
}
func (m *HerdCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HerdCommand.Merge(m, src)
}
func (m *HerdCommand) XXX_Size() int {
	return xxx_messageInfo_HerdCommand.Size(m)
}
func (m *HerdCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_HerdCommand.DiscardUnknown(m)
}

var xxx_messageInfo_HerdCommand proto.InternalMessageInfo

func (m *HerdCommand) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *HerdCommand) GetData1() int64 {
	if m != nil {
		return m.Data1
	}
	return 0
}

func (m *HerdCommand) GetData2() int64 {
	if m != nil {
		return m.Data2
	}
	return 0
}

func (m *HerdCommand) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func init() {
	proto.RegisterType((*HerdCommand)(nil), "main.HerdCommand")
}

func init() { proto.RegisterFile("herdcommand.proto", fileDescriptor_c2a1723f8d5a273c) }

var fileDescriptor_c2a1723f8d5a273c = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x48, 0x2d, 0x4a,
	0x49, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9,
	0x4d, 0xcc, 0xcc, 0x53, 0xca, 0xe5, 0xe2, 0xf6, 0x48, 0x2d, 0x4a, 0x71, 0x86, 0x48, 0x09, 0x89,
	0x71, 0xb1, 0x15, 0x97, 0x24, 0x96, 0x94, 0x16, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x41,
	0x79, 0x42, 0x22, 0x5c, 0xac, 0x29, 0x89, 0x25, 0x89, 0x86, 0x12, 0x4c, 0x60, 0x61, 0x08, 0x07,
	0x26, 0x6a, 0x24, 0xc1, 0x8c, 0x10, 0x35, 0x12, 0x92, 0xe2, 0xe2, 0x48, 0x49, 0x4d, 0x4c, 0xc9,
	0xc9, 0xcc, 0x4b, 0x95, 0x60, 0x01, 0x4b, 0xc0, 0xf9, 0x49, 0x6c, 0x60, 0xbb, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x38, 0xba, 0x48, 0x90, 0x90, 0x00, 0x00, 0x00,
}
